version: '3.8'

volumes:
  rabbitmq_data:
  pgdata:

services:
  attendee1:
    build:
      context: .
      dockerfile: dockerfile_attendee
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5003:5003"
    networks:
      - kong-net

  attendee2:
    build:
      context: .
      dockerfile: dockerfile_attendee
    restart: always
    env_file:
      - ggnr.env
    networks:
      - kong-net

  event1:
    build:
      context: .
      dockerfile: dockerfile_event
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5000:5000"
    networks:
      - kong-net

  event2:
    build:
      context: .
      dockerfile: dockerfile_event
    restart: always
    env_file:
      - ggnr.env
    networks:
      - kong-net

  payment1:
    build:
      context: .
      dockerfile: dockerfile_payment
    restart: always
    env_file:
      - .env
    ports:
      - "5011:5011"
    networks:
      - kong-net

  payment2:
    build:
      context: .
      dockerfile: dockerfile_payment
    restart: always
    env_file:
      - .env
    networks:
      - kong-net

  search:
    build:
      context: .
      dockerfile: dockerfile_search
    restart: always
    env_file:
      - .env
    ports:
      - "5009:5009"
    networks:
      - kong-net

  ticket1:
    build:
      context: .
      dockerfile: dockerfile_ticket
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5008:5008"
    networks:
      - kong-net

  ticket2:
    build:
      context: .
      dockerfile: dockerfile_ticket
    restart: always
    env_file:
      - ggnr.env
    networks:
      - kong-net

  user1:
    build:
      context: .
      dockerfile: dockerfile_user
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5005:5005"
    networks:
      - kong-net
      
  user2:
    build:
      context: .
      dockerfile: dockerfile_user
    restart: always
    env_file:
      - ggnr.env
    networks:
      - kong-net

  registration1:
    build:
      context: .
      dockerfile: dockerfile_registration
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5006:5006"
    depends_on:
      - event1
      - attendee1
      - ticket1
    networks:
      - kong-net

  registration2:
    build:
      context: .
      dockerfile: dockerfile_registration
    restart: always
    env_file:
      - ggnr.env
    depends_on:
      - event1
      - attendee1
      - ticket1
    networks:
      - kong-net

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - kong-net

  event_management1:
    build:
      context: .
      dockerfile: dockerfile_event_management
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5100:5100"
    depends_on:
      - event1
      - user1
      - search
      - notification1
    networks:
      - kong-net

  event_management2:
    build:
      context: .
      dockerfile: dockerfile_event_management
    restart: always
    env_file:
      - ggnr.env
    depends_on:
      - event1
      - user1
      - search
      - notification1
    networks:
      - kong-net

  notification1:
    build:
      context: .
      dockerfile: dockerfile_notification
    restart: always
    env_file:
      - ggnr.env
    depends_on:
      - rabbitmq
    ports:
      - "5010:5010"
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      exchangename: notification_topic
      exchangetype: topic
    networks:
      - kong-net

  notification2:
    build:
      context: .
      dockerfile: dockerfile_notification
    restart: always
    env_file:
      - ggnr.env
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      exchangename: notification_topic
      exchangetype: topic
    networks:
      - kong-net    

  notification_log:
    build:
      context: .
      dockerfile: dockerfile_notification_log
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification_Log
      PYTHONUNBUFFERED: 1
    networks:
      - kong-net

  notification_error:
    build:
      context: .
      dockerfile: dockerfile_notification_error
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      e_queue_name: Error
      PYTHONUNBUFFERED: 1
    networks:
      - kong-net

  custom_notification1:
    build:
      context: .
      dockerfile: dockerfile_custom_notification
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5200:5200"
    depends_on:
      - attendee1
      - user1
      - notification1
    networks:
      - kong-net

  custom_notification2:
    build:
      context: .
      dockerfile: dockerfile_custom_notification
    restart: always
    env_file:
      - ggnr.env
    depends_on:
      - attendee1
      - user1
      - notification1
    networks:
      - kong-net

  kong-database:
    image: postgres:15 # tested 20231101; Ref: https://docs.konghq.com/gateway/latest/support/third-party/
    platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data


  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong/kong-gateway:3.2.2.5 # tested 20231101
    platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    command: "kong migrations bootstrap"
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong/kong-gateway:3.2.2.5 # tested 20231101
    platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-migration
    ports: # https://docs.konghq.com/gateway/latest/production/networking/default-ports/
      - "8000:8000" # Takes incoming HTTP traffic from Consumers, and forwards it to upstream Services.
      - "8443:8443" # Takes incoming HTTPS traffic from Consumers, and forwards it to upstream Services.
      - "8001:8001" # Admin API. Listens for calls from the command line over HTTP.
      - "8444:8444" # Admin API. Listens for calls from the command line over HTTPS.
      - "8002:8002" # Kong Manager (GUI). Listens for HTTP traffic.
      - "8445:8445" # Kong Manager (GUI). Listens for HTTPS traffic.
      - "8003:8003" # Dev Portal. Listens for HTTP traffic, assuming Dev Portal is enabled.
      - "8446:8446" # Dev Portal. Listens for HTTP traffic, assuming Dev Portal is enabled.
      - "8004:8004" # Dev Portal /files traffic over HTTPS, assuming the Dev Portal is enabled.
      - "8447:8447" # Dev Portal /files traffic over HTTPS, assuming the Dev Portal is enabled.
      
networks:
  kong-net:
    driver: bridge
    name: kong-net


