version: '3.8'

services:
  attendee:
    build:
      context: .
      dockerfile: dockerfile_attendee
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5003:5003"
    networks:
      - ggnr_ticket

  event:
    build:
      context: .
      dockerfile: dockerfile_event
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5000:5000"
    networks:
      - ggnr_network
      - ggnr_ticket

  payment:
    build:
      context: .
      dockerfile: dockerfile_payment
    restart: always
    env_file:
      - .env
    ports:
      - "5011:5011"

  search:
    build:
      context: .
      dockerfile: dockerfile_search
    restart: always
    env_file:
      - .env
    ports:
      - "5009:5009"
    networks:
      - ggnr_network

  ticket:
    build:
      context: .
      dockerfile: dockerfile_ticket
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5008:5008"
    networks:
      - ggnr_ticket

  user:
    build:
      context: .
      dockerfile: dockerfile_user
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5005:5005"
    networks:
      - ggnr_network

  registration:
    build:
      context: .
      dockerfile: dockerfile_registration
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5006:5006"
    depends_on:
      - event
      - attendee
      - ticket
    networks:
      - ggnr_ticket
    

  event_management:
    build:
      context: .
      dockerfile: dockerfile_event_management
    restart: always
    env_file:
      - ggnr.env
    ports:
      - "5100:5100"
    depends_on:
      - event
      - user
      - search
    networks:
      - ggnr_network
      
networks:
  ggnr_network:
    driver: bridge
  ggnr_ticket:
    driver: bridge

