# Use an official Ruby runtime as a parent image
FROM ruby:2.7

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install any needed packages specified in Gemfile
RUN gem install bundler -v 1.17.2
RUN bundle install

# Copy the rest of the application into the container
COPY . .

# Run search.rb when the container launches
CMD ["bundle", "exec", "ruby", "./search.rb"]
